// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seckill-collection-rpc.proto

package collection;

public final class SeckillCollectionRpc {
  private SeckillCollectionRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CollectionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CollectionMessage)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code CollectionMessage}
   */
  public static final class CollectionMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CollectionMessage)
      CollectionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CollectionMessage.newBuilder() to construct.
    private CollectionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CollectionMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CollectionMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return collection.SeckillCollectionRpc.internal_static_CollectionMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return collection.SeckillCollectionRpc.internal_static_CollectionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              collection.SeckillCollectionRpc.CollectionMessage.class, collection.SeckillCollectionRpc.CollectionMessage.Builder.class);
    }

    public interface CommonRelyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CollectionMessage.CommonRely)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      int getCode();
    }
    /**
     * Protobuf type {@code CollectionMessage.CommonRely}
     */
    public static final class CommonRely extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CollectionMessage.CommonRely)
        CommonRelyOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CommonRely.newBuilder() to construct.
      private CommonRely(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CommonRely() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new CommonRely();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CommonRely_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CommonRely_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                collection.SeckillCollectionRpc.CollectionMessage.CommonRely.class, collection.SeckillCollectionRpc.CollectionMessage.CommonRely.Builder.class);
      }

      public static final int CODE_FIELD_NUMBER = 1;
      private int code_ = 0;
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (code_ != 0) {
          output.writeInt32(1, code_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, code_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof collection.SeckillCollectionRpc.CollectionMessage.CommonRely)) {
          return super.equals(obj);
        }
        collection.SeckillCollectionRpc.CollectionMessage.CommonRely other = (collection.SeckillCollectionRpc.CollectionMessage.CommonRely) obj;

        if (getCode()
            != other.getCode()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(collection.SeckillCollectionRpc.CollectionMessage.CommonRely prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CollectionMessage.CommonRely}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CollectionMessage.CommonRely)
          collection.SeckillCollectionRpc.CollectionMessage.CommonRelyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CommonRely_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CommonRely_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  collection.SeckillCollectionRpc.CollectionMessage.CommonRely.class, collection.SeckillCollectionRpc.CollectionMessage.CommonRely.Builder.class);
        }

        // Construct using collection.SeckillCollectionRpc.CollectionMessage.CommonRely.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          code_ = 0;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CommonRely_descriptor;
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.CommonRely getDefaultInstanceForType() {
          return collection.SeckillCollectionRpc.CollectionMessage.CommonRely.getDefaultInstance();
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.CommonRely build() {
          collection.SeckillCollectionRpc.CollectionMessage.CommonRely result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.CommonRely buildPartial() {
          collection.SeckillCollectionRpc.CollectionMessage.CommonRely result = new collection.SeckillCollectionRpc.CollectionMessage.CommonRely(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(collection.SeckillCollectionRpc.CollectionMessage.CommonRely result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.code_ = code_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof collection.SeckillCollectionRpc.CollectionMessage.CommonRely) {
            return mergeFrom((collection.SeckillCollectionRpc.CollectionMessage.CommonRely)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(collection.SeckillCollectionRpc.CollectionMessage.CommonRely other) {
          if (other == collection.SeckillCollectionRpc.CollectionMessage.CommonRely.getDefaultInstance()) return this;
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  code_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int code_ ;
        /**
         * <pre>
         * 状态码
         * </pre>
         *
         * <code>int32 code = 1;</code>
         * @return The code.
         */
        @java.lang.Override
        public int getCode() {
          return code_;
        }
        /**
         * <pre>
         * 状态码
         * </pre>
         *
         * <code>int32 code = 1;</code>
         * @param value The code to set.
         * @return This builder for chaining.
         */
        public Builder setCode(int value) {
          
          code_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 状态码
         * </pre>
         *
         * <code>int32 code = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          code_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CollectionMessage.CommonRely)
      }

      // @@protoc_insertion_point(class_scope:CollectionMessage.CommonRely)
      private static final collection.SeckillCollectionRpc.CollectionMessage.CommonRely DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new collection.SeckillCollectionRpc.CollectionMessage.CommonRely();
      }

      public static collection.SeckillCollectionRpc.CollectionMessage.CommonRely getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CommonRely>
          PARSER = new com.google.protobuf.AbstractParser<CommonRely>() {
        @java.lang.Override
        public CommonRely parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<CommonRely> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CommonRely> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public collection.SeckillCollectionRpc.CollectionMessage.CommonRely getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface CreateCollectionReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CollectionMessage.CreateCollectionReq)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return The userId.
       */
      java.lang.String getUserId();
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return The bytes for userId.
       */
      com.google.protobuf.ByteString
          getUserIdBytes();

      /**
       * <pre>
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The password.
       */
      java.lang.String getPassword();
      /**
       * <pre>
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      com.google.protobuf.ByteString
          getPasswordBytes();
    }
    /**
     * Protobuf type {@code CollectionMessage.CreateCollectionReq}
     */
    public static final class CreateCollectionReq extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CollectionMessage.CreateCollectionReq)
        CreateCollectionReqOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CreateCollectionReq.newBuilder() to construct.
      private CreateCollectionReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CreateCollectionReq() {
        userId_ = "";
        password_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new CreateCollectionReq();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CreateCollectionReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CreateCollectionReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.class, collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.Builder.class);
      }

      public static final int USER_ID_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object userId_ = "";
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>string user_id = 1;</code>
       * @return The bytes for userId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASSWORD_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object password_ = "";
      /**
       * <pre>
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The password.
       */
      @java.lang.Override
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq)) {
          return super.equals(obj);
        }
        collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq other = (collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq) obj;

        if (!getUserId()
            .equals(other.getUserId())) return false;
        if (!getPassword()
            .equals(other.getPassword())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId().hashCode();
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CollectionMessage.CreateCollectionReq}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CollectionMessage.CreateCollectionReq)
          collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReqOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CreateCollectionReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CreateCollectionReq_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.class, collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.Builder.class);
        }

        // Construct using collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          userId_ = "";
          password_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_CreateCollectionReq_descriptor;
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq getDefaultInstanceForType() {
          return collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.getDefaultInstance();
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq build() {
          collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq buildPartial() {
          collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq result = new collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.userId_ = userId_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.password_ = password_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq) {
            return mergeFrom((collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq other) {
          if (other == collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq.getDefaultInstance()) return this;
          if (!other.getUserId().isEmpty()) {
            userId_ = other.userId_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getPassword().isEmpty()) {
            password_ = other.password_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  userId_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  password_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object userId_ = "";
        /**
         * <pre>
         *用户id
         * </pre>
         *
         * <code>string user_id = 1;</code>
         * @return The userId.
         */
        public java.lang.String getUserId() {
          java.lang.Object ref = userId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            userId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *用户id
         * </pre>
         *
         * <code>string user_id = 1;</code>
         * @return The bytes for userId.
         */
        public com.google.protobuf.ByteString
            getUserIdBytes() {
          java.lang.Object ref = userId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *用户id
         * </pre>
         *
         * <code>string user_id = 1;</code>
         * @param value The userId to set.
         * @return This builder for chaining.
         */
        public Builder setUserId(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          userId_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户id
         * </pre>
         *
         * <code>string user_id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearUserId() {
          userId_ = getDefaultInstance().getUserId();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户id
         * </pre>
         *
         * <code>string user_id = 1;</code>
         * @param value The bytes for userId to set.
         * @return This builder for chaining.
         */
        public Builder setUserIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          userId_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object password_ = "";
        /**
         * <pre>
         * </pre>
         *
         * <code>string password = 2;</code>
         * @return The password.
         */
        public java.lang.String getPassword() {
          java.lang.Object ref = password_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            password_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * </pre>
         *
         * <code>string password = 2;</code>
         * @return The bytes for password.
         */
        public com.google.protobuf.ByteString
            getPasswordBytes() {
          java.lang.Object ref = password_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            password_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * </pre>
         *
         * <code>string password = 2;</code>
         * @param value The password to set.
         * @return This builder for chaining.
         */
        public Builder setPassword(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          password_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * </pre>
         *
         * <code>string password = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPassword() {
          password_ = getDefaultInstance().getPassword();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <pre>
         * </pre>
         *
         * <code>string password = 2;</code>
         * @param value The bytes for password to set.
         * @return This builder for chaining.
         */
        public Builder setPasswordBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          password_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CollectionMessage.CreateCollectionReq)
      }

      // @@protoc_insertion_point(class_scope:CollectionMessage.CreateCollectionReq)
      private static final collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq();
      }

      public static collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CreateCollectionReq>
          PARSER = new com.google.protobuf.AbstractParser<CreateCollectionReq>() {
        @java.lang.Override
        public CreateCollectionReq parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<CreateCollectionReq> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<CreateCollectionReq> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public collection.SeckillCollectionRpc.CollectionMessage.CreateCollectionReq getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface UpdateCollectionReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CollectionMessage.UpdateCollectionReq)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return The userName.
       */
      java.lang.String getUserName();
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return The bytes for userName.
       */
      com.google.protobuf.ByteString
          getUserNameBytes();

      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The password.
       */
      java.lang.String getPassword();
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      com.google.protobuf.ByteString
          getPasswordBytes();

      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>string id = 3;</code>
       * @return The id.
       */
      java.lang.String getId();
      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>string id = 3;</code>
       * @return The bytes for id.
       */
      com.google.protobuf.ByteString
          getIdBytes();
    }
    /**
     * Protobuf type {@code CollectionMessage.UpdateCollectionReq}
     */
    public static final class UpdateCollectionReq extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CollectionMessage.UpdateCollectionReq)
        UpdateCollectionReqOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UpdateCollectionReq.newBuilder() to construct.
      private UpdateCollectionReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UpdateCollectionReq() {
        userName_ = "";
        password_ = "";
        id_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new UpdateCollectionReq();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_UpdateCollectionReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_UpdateCollectionReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.class, collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.Builder.class);
      }

      public static final int USER_NAME_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object userName_ = "";
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return The userName.
       */
      @java.lang.Override
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string user_name = 1;</code>
       * @return The bytes for userName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASSWORD_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object password_ = "";
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The password.
       */
      @java.lang.Override
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *用户密码
       * </pre>
       *
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ID_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object id_ = "";
      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>string id = 3;</code>
       * @return The id.
       */
      @java.lang.Override
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *主键id
       * </pre>
       *
       * <code>string id = 3;</code>
       * @return The bytes for id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq)) {
          return super.equals(obj);
        }
        collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq other = (collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq) obj;

        if (!getUserName()
            .equals(other.getUserName())) return false;
        if (!getPassword()
            .equals(other.getPassword())) return false;
        if (!getId()
            .equals(other.getId())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CollectionMessage.UpdateCollectionReq}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CollectionMessage.UpdateCollectionReq)
          collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReqOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_UpdateCollectionReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_UpdateCollectionReq_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.class, collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.Builder.class);
        }

        // Construct using collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          userName_ = "";
          password_ = "";
          id_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return collection.SeckillCollectionRpc.internal_static_CollectionMessage_UpdateCollectionReq_descriptor;
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq getDefaultInstanceForType() {
          return collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.getDefaultInstance();
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq build() {
          collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq buildPartial() {
          collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq result = new collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.userName_ = userName_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.password_ = password_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.id_ = id_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq) {
            return mergeFrom((collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq other) {
          if (other == collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq.getDefaultInstance()) return this;
          if (!other.getUserName().isEmpty()) {
            userName_ = other.userName_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getPassword().isEmpty()) {
            password_ = other.password_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (!other.getId().isEmpty()) {
            id_ = other.id_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  userName_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  password_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  id_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object userName_ = "";
        /**
         * <pre>
         *用户名
         * </pre>
         *
         * <code>string user_name = 1;</code>
         * @return The userName.
         */
        public java.lang.String getUserName() {
          java.lang.Object ref = userName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            userName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *用户名
         * </pre>
         *
         * <code>string user_name = 1;</code>
         * @return The bytes for userName.
         */
        public com.google.protobuf.ByteString
            getUserNameBytes() {
          java.lang.Object ref = userName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *用户名
         * </pre>
         *
         * <code>string user_name = 1;</code>
         * @param value The userName to set.
         * @return This builder for chaining.
         */
        public Builder setUserName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          userName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户名
         * </pre>
         *
         * <code>string user_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearUserName() {
          userName_ = getDefaultInstance().getUserName();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户名
         * </pre>
         *
         * <code>string user_name = 1;</code>
         * @param value The bytes for userName to set.
         * @return This builder for chaining.
         */
        public Builder setUserNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          userName_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object password_ = "";
        /**
         * <pre>
         *用户密码
         * </pre>
         *
         * <code>string password = 2;</code>
         * @return The password.
         */
        public java.lang.String getPassword() {
          java.lang.Object ref = password_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            password_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *用户密码
         * </pre>
         *
         * <code>string password = 2;</code>
         * @return The bytes for password.
         */
        public com.google.protobuf.ByteString
            getPasswordBytes() {
          java.lang.Object ref = password_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            password_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *用户密码
         * </pre>
         *
         * <code>string password = 2;</code>
         * @param value The password to set.
         * @return This builder for chaining.
         */
        public Builder setPassword(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          password_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户密码
         * </pre>
         *
         * <code>string password = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPassword() {
          password_ = getDefaultInstance().getPassword();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <pre>
         *用户密码
         * </pre>
         *
         * <code>string password = 2;</code>
         * @param value The bytes for password to set.
         * @return This builder for chaining.
         */
        public Builder setPasswordBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          password_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private java.lang.Object id_ = "";
        /**
         * <pre>
         *主键id
         * </pre>
         *
         * <code>string id = 3;</code>
         * @return The id.
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *主键id
         * </pre>
         *
         * <code>string id = 3;</code>
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *主键id
         * </pre>
         *
         * <code>string id = 3;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          id_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *主键id
         * </pre>
         *
         * <code>string id = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          id_ = getDefaultInstance().getId();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <pre>
         *主键id
         * </pre>
         *
         * <code>string id = 3;</code>
         * @param value The bytes for id to set.
         * @return This builder for chaining.
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          id_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CollectionMessage.UpdateCollectionReq)
      }

      // @@protoc_insertion_point(class_scope:CollectionMessage.UpdateCollectionReq)
      private static final collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq();
      }

      public static collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UpdateCollectionReq>
          PARSER = new com.google.protobuf.AbstractParser<UpdateCollectionReq>() {
        @java.lang.Override
        public UpdateCollectionReq parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<UpdateCollectionReq> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<UpdateCollectionReq> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public collection.SeckillCollectionRpc.CollectionMessage.UpdateCollectionReq getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof collection.SeckillCollectionRpc.CollectionMessage)) {
        return super.equals(obj);
      }
      collection.SeckillCollectionRpc.CollectionMessage other = (collection.SeckillCollectionRpc.CollectionMessage) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static collection.SeckillCollectionRpc.CollectionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(collection.SeckillCollectionRpc.CollectionMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CollectionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CollectionMessage)
        collection.SeckillCollectionRpc.CollectionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                collection.SeckillCollectionRpc.CollectionMessage.class, collection.SeckillCollectionRpc.CollectionMessage.Builder.class);
      }

      // Construct using collection.SeckillCollectionRpc.CollectionMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return collection.SeckillCollectionRpc.internal_static_CollectionMessage_descriptor;
      }

      @java.lang.Override
      public collection.SeckillCollectionRpc.CollectionMessage getDefaultInstanceForType() {
        return collection.SeckillCollectionRpc.CollectionMessage.getDefaultInstance();
      }

      @java.lang.Override
      public collection.SeckillCollectionRpc.CollectionMessage build() {
        collection.SeckillCollectionRpc.CollectionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public collection.SeckillCollectionRpc.CollectionMessage buildPartial() {
        collection.SeckillCollectionRpc.CollectionMessage result = new collection.SeckillCollectionRpc.CollectionMessage(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof collection.SeckillCollectionRpc.CollectionMessage) {
          return mergeFrom((collection.SeckillCollectionRpc.CollectionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(collection.SeckillCollectionRpc.CollectionMessage other) {
        if (other == collection.SeckillCollectionRpc.CollectionMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CollectionMessage)
    }

    // @@protoc_insertion_point(class_scope:CollectionMessage)
    private static final collection.SeckillCollectionRpc.CollectionMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new collection.SeckillCollectionRpc.CollectionMessage();
    }

    public static collection.SeckillCollectionRpc.CollectionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CollectionMessage>
        PARSER = new com.google.protobuf.AbstractParser<CollectionMessage>() {
      @java.lang.Override
      public CollectionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CollectionMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CollectionMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public collection.SeckillCollectionRpc.CollectionMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CollectionMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CollectionMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CollectionMessage_CommonRely_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CollectionMessage_CommonRely_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CollectionMessage_CreateCollectionReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CollectionMessage_CreateCollectionReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CollectionMessage_UpdateCollectionReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CollectionMessage_UpdateCollectionReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034seckill-collection-rpc.proto\"\261\001\n\021Colle" +
      "ctionMessage\032\032\n\nCommonRely\022\014\n\004code\030\001 \001(\005" +
      "\0328\n\023CreateCollectionReq\022\017\n\007user_id\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\t\032F\n\023UpdateCollectionRe" +
      "q\022\021\n\tuser_name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\n" +
      "\n\002id\030\003 \001(\t2\300\001\n\030SeckillCollectionService\022" +
      "Q\n\006create\022&.CollectionMessage.CreateColl" +
      "ectionReq\032\035.CollectionMessage.CommonRely" +
      "\"\000\022Q\n\006update\022&.CollectionMessage.UpdateC" +
      "ollectionReq\032\035.CollectionMessage.CommonR" +
      "ely\"\000B\014\n\ncollectionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CollectionMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CollectionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CollectionMessage_descriptor,
        new java.lang.String[] { });
    internal_static_CollectionMessage_CommonRely_descriptor =
      internal_static_CollectionMessage_descriptor.getNestedTypes().get(0);
    internal_static_CollectionMessage_CommonRely_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CollectionMessage_CommonRely_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_CollectionMessage_CreateCollectionReq_descriptor =
      internal_static_CollectionMessage_descriptor.getNestedTypes().get(1);
    internal_static_CollectionMessage_CreateCollectionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CollectionMessage_CreateCollectionReq_descriptor,
        new java.lang.String[] { "UserId", "Password", });
    internal_static_CollectionMessage_UpdateCollectionReq_descriptor =
      internal_static_CollectionMessage_descriptor.getNestedTypes().get(2);
    internal_static_CollectionMessage_UpdateCollectionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CollectionMessage_UpdateCollectionReq_descriptor,
        new java.lang.String[] { "UserName", "Password", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
